### ISSUE TITLE
unable to dim lights or execute scenes

### ISSUE THREAD

**Issue by bluntiless** [mrhornsby/HAP-NodeJS#5]
Having trouble getting the server to dim or increase the brightness of my lights. It only seems to switch them on or off. In addition I cannot seem to execute scenes anymore. Not sure if this is since I updated to iOS 10 or if its the WiFi link and its software which was automatically updated to firmware v2.93.
(callback=true) "Transmit fail" 
is what it says in terminal when it fails to execute a scene!

**Comment by mrhornsby** [comment]
Hi,

I'm running iOS 10 and firmware U2.93T on the wifi link. I use the built in apple Home app which seems to work (although it hangs for 10-15 seconds after each command).

However I've just tried using the Eve app and can replicate the "Transmit Fail" message. I'll investigate further this weekend and update the issues once I've figured it out.

Mark

**Comment by mrhornsby** [comment]
It seems they've changed the firmware so that you can't send messages as frequently as was previously possible. Can you try changing the delay (in milliseconds) in lib/util/lightwave.js:

``` javascript
setInterval(sendFromQueue, 250);
```

I would suggest trying maybe 500 and seeing if that fixes the problem.

**Comment by bluntiless** [comment]
Hi Mark,

I also have had the 10-15  second delay with the Apple Home app. Also the home app seems to struggle with dimming my lights, but interestingly dimming works better with Eve app.

**Comment by bluntiless** [comment]
Hi,
I will try that later when I get home from work. 

Thanks for the assistance

**Comment by mrhornsby** [comment]
I've just had a quick test - you get transmit fails up to about 750ms - with 800ms I've seen no failures so I'll change this (unfortunately it means your dimming will be slightly less responsive). I'm also going to merge the latest 0.4.13 release of KhaosT's code to see if this fixes the unresponsive nature of the Home app.

**Comment by mrhornsby** [comment]
The unresponsiveness of the Home app was due to the fact that it sends both an on and a dim message for operations on a light - I was responding to the dim and ignoring the on message - the app hangs until it times out - this is now fixed in the latest version.

**Comment by bluntiless** [comment]
Hi Mark

I took your advice and changed the interval to 800 and also updated it to the latest version. Unfortunately I have encountered a couple of issues.

Firstly the server still seems to be slow to respond and sometimes Siri cannot find any of the devices, even though they are shown in the home app. Also it appears to be more responsive if I am not connected to my WiFi network and connecting remotely from my mobile network! This would appear to be, I assume because the AppleTV 4 and iPad are now used as home hubs for remote access. Also the ATV4 Siri remote and iPad Siri work very well for controlling the accessories. The trouble just seems to be with my iPhone.

Secondly I have another issue which just randomly started today. When I try to start the server, I now get this error

HAP-NodeJS starting...
Parsing accessory: LightwaveRFLink_accessory.js
/home/pi/HAP-NodeJS/accessories/LightwaveRFLink_accessory.js:9
LWRF .init()

Any advice would be greatly appreciated

Best wishes and Merry Christmas

Wayne

Sent from my iPad Siri

On 4 Nov 2016, at 17:55, Mark <notifications@github.com<mailto:notifications@github.com>> wrote:


The unresponsiveness of the Home app was due to the fact that it sends both an on and a dim message for operations on a light - I was responding to the dim and ignoring the on message - the app hangs until it times out - this is now fixed in the latest version.

-

**Comment by mrhornsby** [comment]
Hi Wayne,

Merry Christmas!

There was another small change I made which will likely fix this - can you download https://github.com/mrhornsby/HAP-NodeJS/releases/tag/v0.4.3 and give this a try?

I've included a technical explanation below, but v0.4.3 should make things much better.

Mark

----

Some HomeKit dimming code sends a stream of messages as you change the dim level, so you might drag a slider in 100ms from 100% to 50% and this will send maybe 15-20 updates as you drag. With an 800ms delay this would take about 15 seconds to finish dimming to the correct level. I used to de-duplicate messages for a given room and device, but when apps send an on, dim 100% sequence in quick succession I would drop the on message, causing HomeKit to hang and get no response. I now de-duplicate by the type of message as well, so an on, dim 100% will both be executed. I'm thinking about making another change to fire the callback even when I drop a message, but this could result in HomeKit thinking a light is in one state when it's actually in another.
